### ISSUE TITLE
Understanding the wpengine function

### ISSUE THREAD

**Issue by aManNamedJed** [wearefine/wpengine-jenkins-shared-libraries#2]
Thank you for sharing this online. I see the `call(body)` function within the Groovy file. I'm not sure what that body object looks like. Would you guys show just a basic example of your Jenkinsfile where that is called in?

**Comment by aManNamedJed** [comment]
This is what I have so far:
```
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                 def wpengine = load("vars/wpengine.groovy")
                 wpengine.call()
            }
        }
    }
}
```

**Comment by cpitkin** [comment]
Hey, @jdarrohn  thanks for taking a look at this shared library. 

All the stuff you need to setup to get this code to run is in the repo. The code is set up as a scripted Jenkins pipeline shared library with a custom built DSL (more on that [here](https://jenkins.io/doc/book/pipeline/shared-libraries/#defining-a-more-structured-dsl)). This helps keep the Jenkinsfile that is kept in the app repo much simpler and allows you to update the deployment code without needing to update the app repos. For a complete example of the Jenkinsfile that should be used in the application repo, you can look in the README [here](https://github.com/wearefine/wpengine-jenkins-shared-libraries#jenkinsfile) or at the Jenkinsfile.example in the root of this repo. 

If you're new to shared libraries and pipeline jobs I would suggest you look at the [prereqisites](https://github.com/wearefine/wpengine-jenkins-shared-libraries#prerequisites) section of the README to get a better understanding of how they work. Everything here is build using scripted pipelines since they offer greater flexibility and customization.

**Comment by cpitkin** [comment]
Since there has been no further discussion I am closing this issue. Feel free to reopen if you're still having trouble.
